### PR TITLE
add dvb-s2x and associated tests

### PR DESCRIPTION
**Pull request by harrison-caudill**
This change is [Reviewable](https://reviewable.io/reviews/harrison-caudill/pylink/2)

### CODE REVIEW

**Comment by mikesokolsky** [comment]
There's not enough documentation to really follow this right now without reading through the source code itself.  The readme refers to the examples, but they are not commented.   Is there a place where the classes and their relationships are defined?  There's a little documentation in the README about Tributaries, but exactly what they are and how the fit into the larger context of the package is missing for me.  Also, docstrings?

---

Reviewed 13 of 33 files at r1.
Review status: 12 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 1 at r1](https://reviewable.io:443/reviews/harrison-caudill/pylink/2#-KXqgADdMbu28qxCFiSY:-KXqgADeUfBbqrUYKDIC:bahv9yq) ([raw file](https://github.com/harrison-caudill/pylink/blob/27c18b09f78ee732e9fa32914f431024f460a88e/README.md#L1)):*
> ```Markdown
> Python Link Budget Calculation/Management and General Modelling
> ```

Generally this feels more like it's explaining decisions and talking about gotchas rather than introducing what the package is, what it does, and how to use it.  What is a tributary, why is this a DAG and how does that work, etc?  See the PR-level comment.

---

*[README.md, line 6 at r1](https://reviewable.io:443/reviews/harrison-caudill/pylink/2#-KXqVZ3KId5O1ObeMi7u:-KXqVZ3LOo409sgQiX8j:bn0cf07) ([raw file](https://github.com/harrison-caudill/pylink/blob/27c18b09f78ee732e9fa32914f431024f460a88e/README.md#L6)):*
> ```Markdown
> This software package is meant to replace the manual-intensive
> spreadsheet method.  This package is intended to permit the following
> major changes in our methodology:
> ```

who's methodology?

---

*[README.md, line 33 at r1](https://reviewable.io:443/reviews/harrison-caudill/pylink/2#-KXqWWMtJWjhGPMCVHNv:-KXqWWMtJWjhGPMCVHNw:b-jhgrwg) ([raw file](https://github.com/harrison-caudill/pylink/blob/27c18b09f78ee732e9fa32914f431024f460a88e/README.md#L33)):*
> ```Markdown
>  * `python setup.py install -f`
>  * `pip install -r requirements.txt`
>  * `d=${HOME}/.matplotlib; mkdir -p ${d} ; cd ${d} ; fc-list` matplotlib issue #2919
> ```

recognize this is a potential issue, but it doesn't seem appropriate for a general installation guide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/harrison-caudill/pylink/2#-:-KXqh-PYAr-6B8rzkvjg:b-1esypj)*

**Comment by harrison-caudill** [comment]
Review status: 10 of 30 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 1 at r1](https://reviewable.io:443/reviews/harrison-caudill/pylink/2#-KXqgADdMbu28qxCFiSY:-KXrPbDd_wB50zcLBJ4m:b-896fix) ([raw file](https://github.com/harrison-caudill/pylink/blob/27c18b09f78ee732e9fa32914f431024f460a88e/README.md#L1)):*
<details><summary><i>Previously, mikesokolsky (Mike) wrote…</i></summary><blockquote>

Generally this feels more like it's explaining decisions and talking about gotchas rather than introducing what the package is, what it does, and how to use it.  What is a tributary, why is this a DAG and how does that work, etc?  See the PR-level comment.
</blockquote></details>

Done.

---

*[README.md, line 6 at r1](https://reviewable.io:443/reviews/harrison-caudill/pylink/2#-KXqVZ3KId5O1ObeMi7u:-KXrPcuVD1XdeGKYAoCk:b-896fix) ([raw file](https://github.com/harrison-caudill/pylink/blob/27c18b09f78ee732e9fa32914f431024f460a88e/README.md#L6)):*
<details><summary><i>Previously, mikesokolsky (Mike) wrote…</i></summary><blockquote>

who's methodology?
</blockquote></details>

Done.

---

*[README.md, line 33 at r1](https://reviewable.io:443/reviews/harrison-caudill/pylink/2#-KXqWWMtJWjhGPMCVHNv:-KXrPxIfbrhs65t94M24:bgucvov) ([raw file](https://github.com/harrison-caudill/pylink/blob/27c18b09f78ee732e9fa32914f431024f460a88e/README.md#L33)):*
<details><summary><i>Previously, mikesokolsky (Mike) wrote…</i></summary><blockquote>

recognize this is a potential issue, but it doesn't seem appropriate for a general installation guide.
</blockquote></details>

I've reworded so it doesn't look like a required step, but rather an FYI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/harrison-caudill/pylink/2)*

**Comment by harrison-caudill** [comment]
Review status: 10 of 30 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 33 at r1](https://reviewable.io:443/reviews/harrison-caudill/pylink/2#-KXqWWMtJWjhGPMCVHNv:-KXra8m5XGhZrnBKO4yH:b-896fix) ([raw file](https://github.com/harrison-caudill/pylink/blob/27c18b09f78ee732e9fa32914f431024f460a88e/README.md#L33)):*
<details><summary><i>Previously, harrison-caudill (Harrison Caudill) wrote…</i></summary><blockquote>

I've reworded so it doesn't look like a required step, but rather an FYI.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/harrison-caudill/pylink/2)*

**Comment by harrison-caudill** [comment]
@mikesokolsky outta time -- merging.

**Pull request merged**
